name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install deps
      - name: Install dependencies
        run: npm install
        working-directory: ./fundamentals-app

      # Build app
      - name: Build app
        run: npm run build
        working-directory: ./fundamentals-app

      # Debug step - check dist folder
      - name: Show dist folder
        run: ls -la ./fundamentals-app/dist || echo "dist folder not found"

      # Deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_HILL_0461CA910}}
          action: "upload"
          app_location: "./fundamentals-app" # App source code path
          api_location: ""                   # Api source code path - optional
          output_location: "dist"            # Vite output folder
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
